---
- name: Manage Windows
  hosts: win
  become: false
  gather_facts: false
  collections:
  - community.windows
  tasks:
  - name: Set Windows description only
    win_shell: |
      $OSWMI=Get-WmiObject -class Win32_OperatingSystem
      $OSWMI.Description="My Server 2"
      $OSWMI.put()
  
