---
- name: Manage Windows
  hosts: win
  become: false
  gather_facts: false
  collections:
    - community.windows
  tasks:
  - name: Set Windows description only
    win_computer_description:
      description: Una descripcion de Prueba
    register: task_result
  
