---
- name: Manage Windows
  hosts: win
  become: false
  gather_facts: false
  tasks:
  - name: Set Windows description only
    community.windows.win_computer_description:
      description: Una descripcion de Prueba
    register: task_result  
  
